language: python
sudo: required

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker run --rm --privileged multiarch/qemu-user-static:register

install:
  - docker build --rm --no-cache -t stevebargelt/dasher-rpi .
  - docker push stevebargelt/dasher-rpi

script: true
