language: python
sudo: required

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker run --rm --privileged multiarch/qemu-user-static:register

install:
  - docker build --rm --no-cache -t stevebargelt/dasher-rpi .
  - docker push stevebargelt/dasher-rpi

script: true

notifications:
  slack:
    rooms:
      - secure: ""
    template:
      - "Status=%{result}, Job=%{repository_name}, Build=%{build_number}, URL=%{build_url}, HUB=https://hub.docker.com/r/stevebargelt/dasher-rpi/"
