language: python
sudo: required
services:
- docker
before_install:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker run --rm --privileged multiarch/qemu-user-static:register
install:
- docker build --rm --no-cache -t stevebargelt/dasher-rpi .
- docker push stevebargelt/dasher-rpi
script: true
notifications:
  slack:
    rooms:
      secure: F7Pv3S/A3Gicp96f0pPcRyQbHJLEFmpIU6k49wJ0yT+aSs5MmXJmbX4BtW4IOXwJUd+YJFCqbswvAWTh1m/yKmqecoVZbNqy1PS5Aki0LYzdeUVPRrokEze/A8DWU9nA8q4QchfzxOyIzKnp42edfTceAWeHH4AlJZs8umgerAxRPZXTZC52FDdjvRDkRs2O6bsbMv9Nv7Dk72GGA+IfgVDQIfPPBU/9bs8Rio64fbCMzY/zvCgZdvFIKvhOYrXr8CabqggqMeIXeifZccjDEyzTTANXtxCTd7p2qvp0WT2LWIbvnHLEGZJmJJGFI10uKIrW1hfw2x2K05MbmSuaFE4lYbFDTQrXNZL2DzCUaPzIDR5oLi9ct4y9SFQ6H/Orco6yYlsm/7NSOv13zrUK5R4mSoqb471qDViQPLxK3P/R1qmbQ9agLqggJhWxr9WQ/UIMDkSC7wpTqUe17h5C+XSNq1e/ps4KNSlKEGxWINTbQ6j0h3ZM/L0Qb+RSUAzndOION8GxhSEx+1srV+Qy/2uZW/9qIe7Nf2Np5AFwN91Sc+9oa+qnFXDbV13U4mz2Z4eBA8i+Cv9u8IXZ47EWRmAoX3qSGfTMzFQnKpinkNF11UNT+T+Gobm0mLlA4/AfQrzGarvKi116weQcREXeItH23Sp67QExF7SZUA5zIqc=
    template:
    - Status=%{result}, Job=%{repository_name}, Build=%{build_number}, URL=%{build_url},
      HUB=https://hub.docker.com/r/stevebargelt/dasher-rpi/
  webhooks: 
    - https://webhookmqtt.azurewebsites.net/api/travisMQTT?code=bLydjI9wlj1oj4wTfDMSqiZxXkgIn7RaVJiYl4qR/MKjUCcb7/abIg==
